insert into term (name, accession, uri) values ('exon', 'SO:0000147', 'http://purl.obolibrary.org/obo/SO_0000147');
insert into term (name, accession, uri) values ('intron', 'SO:0000188', 'http://purl.obolibrary.org/obo/SO_0000188');
insert into term (name, accession, uri) values ('five_prime_UTR', 'SO:0000204', 'http://purl.obolibrary.org/obo/SO_0000204');
insert into term (name, accession, uri) values ('three_prime_UTR', 'SO:0000205', 'http://purl.obolibrary.org/obo/SO_0000205');

insert into locus (name, uri) values ('HLA-A', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/0');
insert into locus (name, uri) values ('HLA-B', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/1');
insert into locus (name, uri) values ('HLA-C', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/2');
insert into locus (name, uri) values ('HLA-DPA1', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/3');
insert into locus (name, uri) values ('HLA-DPB1', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/4');
insert into locus (name, uri) values ('HLA-DQA1', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/5');
insert into locus (name, uri) values ('HLA-DQB1', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/6');
insert into locus (name, uri) values ('HLA-DRB1', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/7');
insert into locus (name, uri) values ('HLA-DRB3', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/8');
insert into locus (name, uri) values ('HLA-DRB4', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/9');
insert into locus (name, uri) values ('HLA-DRB5', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/a');
insert into locus (name, uri) values ('HLA-DMA', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/b');
insert into locus (name, uri) values ('HLA-DMB', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/c');
insert into locus (name, uri) values ('HLA-DOA', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/d');
insert into locus (name, uri) values ('HLA-DRA', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/e');
insert into locus (name, uri) values ('HLA-DRB6', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/f');
insert into locus (name, uri) values ('HLA-DRB7', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/g');
insert into locus (name, uri) values ('HLA-E', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/h');
insert into locus (name, uri) values ('HLA-G', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/i');
insert into locus (name, uri) values ('TAP1', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/j');
insert into locus (name, uri) values ('TAP2', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/k');
insert into locus (name, uri) values ('MICA', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/l');
insert into locus (name, uri) values ('HLA-DRB2', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/m');
insert into locus (name, uri) values ('HLA-DRB8', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/n');
insert into locus (name, uri) values ('HLA-DRB9', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/o');
insert into locus (name, uri) values ('HLA-F', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/p');
insert into locus (name, uri) values ('HLA-DOB', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/q');
insert into locus (name, uri) values ('MICB', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/r');
insert into locus (name, uri) values ('HLA-H', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/s');
insert into locus (name, uri) values ('HLA-J', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/t');
insert into locus (name, uri) values ('HLA-K', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/u');
insert into locus (name, uri) values ('HLA-L', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/v');
insert into locus (name, uri) values ('HLA-P', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/w');
insert into locus (name, uri) values ('HLA-V', 'https://gl.nmdp.org/imgt-hla/3.18.0/locus/x');
