# Development Feature Service docker deployment
# Feature service image is built and deployed
service-feature:
  build: .
  ports:
    - 80:8080
    - 81:8081
  links:
    - featuredb
  restart: always

featuredb:
  image: mysql:5.7
  # Open the port in dev, in case you want to connect using SQL Tools eg. SQLDeveloper
  ports:
    - 3306:3306
  environment:
    MYSQL_DATABASE: feature
    MYSQL_ROOT_PASSWORD: supersecretpwd
  volumes:
    - data:/var/lib/mysql

phpmyadmin:
  image: phpmyadmin/phpmyadmin:5.1
  container_name: myadmin
  environment:
   - PMA_ARBITRARY=1
     PMA_HOST=featuredb
  restart: always
  ports:
   - 8080:80
  links:
  - featuredb:db
